  pipeline {
    agent any
    
    
  stages {
    stage('Initial cleanup') {
        steps {
          dir("${WORKSPACE}") {
              deleteDir{}
          }
        }
    }
    stage('Build') {
      steps {
        script {
          sh 'echo "Building Stage"'
        }
      }
    }
    stage('Test') {
      steps {
        script {
          sh 'echo "Testing Stage"'
        }
      }
    }
    stage('Package') {
      steps {
        script {
          sh 'echo "Packaging Stage"'
        }
      }
    }
    stage('Deploy') {
      steps {
        script {
          sh 'echo "Deployment Stage"'
        }
      }
    }
    stage('Clean up') {
      steps {
        script {
          sh 'echo "Clean up Stage"'
        }
      }
    }
    stage('final cleanup') {
      steps {
          cleanWs{}
      }
    }
  }
}
